"""empty message

Revision ID: 812e56118cb2
Revises: 3e7866a7aacd
Create Date: 2021-09-01 16:05:10.148185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812e56118cb2'
down_revision = '3e7866a7aacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comments', 'post_id')
    op.drop_table('likes')
    # ### end Alembic commands ###
